name: CI/CD - democyber

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/democyber:latest
      VERSION: 1.0.0

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Gitleaks scan
        uses: zricethezav/gitleaks-action@v1
        with:
          args: --verbose

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and test Java project
        run: mvn clean verify

      - name: Set version
        run: echo "version=$VERSION" >> $GITHUB_OUTPUT
