name: CI/CD - democyber

# Trigger the workflow on push or pull request to main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/democyber:latest
      VERSION: 1.0.0  # tu peux dÃ©finir une version par dÃ©faut

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # ðŸ” GITLEAKS SECURITY SCAN
      - name: Gitleaks scan
        uses: zricethezav/gitleaks-action@v1
        with:
          args: --verbose

      # Install Java
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # Compile Java code
      - name: Compile Java
        run: mvn compile

      # Build Maven
      - name: Build Java project with Maven
        run: mvn clean package

      # Set version using GITHUB_OUTPUT
      - name: Set version
        run: echo "version=$VERSION" >> $GITHUB_OUTPUT



